### ISSUE TITLE
洋用户的反馈, 几个请求

### ISSUE THREAD

**Issue by jasonliul** [sonyps5201314/SocksCapEx2#3]
资源占用仅仅是Scockscap64的一半, 赞!

1. 很容易误关闭, 请将关闭按钮等同最小化, 只能从tray退出.
2. 代理管理器栏目很多, 请将"状态""延迟"[测试结果], 调整到"代理地址""端口"之后, 方便查看.
3. 按钮栏能否增加"代理管理器", 每次从菜单打开很不便.
4.中国袜子协议[SS/SSR]令人困惑, 能否把相关栏目, 做成可以折叠/展开的样式?
5.一些老牌长效透明代理, 只支持旧系列openssl 1.02, 能否做一个子版本?

**Comment by sonyps5201314** [comment]
1.误关闭了也没事，本软件目前不存在任何后台任务需要一直开着一个后台程序来运行；你可以为你常用的网络程序创建SCE快捷方式，这样就不用每次都进本程序里面来启动你想启动的网络程序了；或者使用全局代理功能，这样除非需要修改本软件的配置信息，否则你不需要启动本软件的界面程序。
2.反正屏幕都很大，能完整显示所有列，没必要调整，放在越后面一般是表示越不重要的信息。
3.从菜单启动也没有多大差别，由于没有美工资源，界面就暂时不想调整了。
4.国外用户不懂这些参数列是什么吗，反正选择常规代理协议时，那些国内协议相关的参数列就会自动置空，所以也不是很影响。
5.这个说的是什么，HTTPS代理协议吗？

还有请不要到处散播在本软件的程序列表中加入了很多其它代理软件的那张图片，你要宣传的话放几个浏览器进去是没关系的，谢谢。

**Comment by jasonliul** [comment]
那是应波斯友的请求做的, 移除就是.
